# Generated by Django 5.0.4 on 2024-05-27 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LinkMarket", "0003_product_business"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="LinkMarket.business",
            ),
        ),
    ]
