# Generated by Django 5.0.4 on 2024-05-28 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LinkMarket", "0005_remove_business_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="LinkMarket.seller",
            ),
        ),
    ]
