# Generated by Django 5.0.4 on 2024-05-28 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LinkMarket", "0006_business_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="LinkMarket.category"
            ),
        ),
    ]
