# Generated by Django 5.0.4 on 2024-05-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LinkMarket", "0009_alter_business_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="user",
            new_name="user_id",
        ),
    ]
