# Generated by Django 5.0.4 on 2024-05-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LinkMarket", "0010_rename_user_business_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="user_id",
            new_name="user",
        ),
    ]
